### ISSUE TITLE
Categorize Apps

### ISSUE THREAD

**Issue by jonathansimmons** [jonathansimmons/config#1]
In the initial list I've just spat our the apps I installed today in basic categories. 

The thought that I'm having is not everyone is a developer.. So what if we have a simple way of toggling the viewable content. All, Developer, Designer etc. 

@joshferrara Thoughts?

**Comment by joshferrara** [comment]
This makes a ton of sense. That way you could tell a family member to go to `http://freshstart.io/basic` and they would see a specific selection of the whole list. 

This would be easy to do with Jekyll and Liquid templates.
