### ISSUE TITLE
Include Useful Websites?

### ISSUE THREAD

**Issue by jonathansimmons** [jonathansimmons/config#2]
Depending on what direction we take this, I wonder if tracking website's we find useful would be interesting. Examples: http://jsbeautifier.org/, http://js2coffee.org/

**Comment by joshferrara** [comment]
I've always wanted to have a good place to have these in once spot. This section could even be laid out almost like a launcher of sorts. Imagining people using `freshstart.io/sites` as a home page in their browser and they can quickly jump to useful sites throughout the day.

This may also be nice to have segmented by need type (dev, designer, basic, etc).

**Comment by jonathansimmons** [comment]
I like the idea of the launcher... Zendesk has a extensions feature in their app where they list partners
It's simple but could be a decent ui point: 
![screen shot 2014-06-05 at 3 22 16 pm](https://cloud.githubusercontent.com/assets/945202/3193155/357b5cae-ecef-11e3-8065-f80c7866a019.png)

The jetpack ui for wordpress also comes to mind.
